/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorButton: typeof import('./src/components/ColorButton.vue')['default']
    ColorButtons: typeof import('./src/components/ColorButtons.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FilterContent: typeof import('./src/components/FilterContent.vue')['default']
    FilterModal: typeof import('./src/components/FilterModal.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
  }
}
